nelmio_security:
    clickjacking:
        paths:
            "^/.*": DENY

    content_type:
        nosniff: true

    referrer_policy:
        enabled: true
        policies:
            - no-referrer
            - strict-origin-when-cross-origin

    csp:
        enabled: true
        content_types:
            - text/html
        compat_headers: false

        enforce:
            default-src:
                - "'self'"

            script-src:
                - "'self'"
                - https://cdnjs.cloudflare.com
                - https://cdn.jsdelivr.net
                - https://unpkg.com
                - https://challenges.cloudflare.com
                - https://*.cloudflare.com
                - https://cloudflare.com
                - https://stackpath.bootstrapcdn.com
                - https://maxcdn.bootstrapcdn.com
                - https://maps.googleapis.com
                - https://maps.gstatic.com
                - https://www.google.com

            style-src:
                - "'self'"
                - "'unsafe-inline'"
                - https://fonts.googleapis.com
                - https://cdnjs.cloudflare.com
                - https://cdn.jsdelivr.net
                - https://unpkg.com
                - https://stackpath.bootstrapcdn.com
                - https://maxcdn.bootstrapcdn.com

            font-src:
                - "'self'"
                - "data:"
                - https://cdnjs.cloudflare.com # ‚Üê indispensable pour Font Awesome
                - https://fonts.gstatic.com
                - https://stackpath.bootstrapcdn.com
                - https://maxcdn.bootstrapcdn.com
                - https://cdn.jsdelivr.net

            img-src:
                - "'self'"
                - "data:"
                - "blob:"
                - https://challenges.cloudflare.com
                - https://*.cloudflare.com
                - https://cdn.jsdelivr.net
                - https://maps.gstatic.com
                - https://maps.googleapis.com
                - https://www.google.com
                - https://*.svgrepo.com

            connect-src:
                - "'self'"
                - https://challenges.cloudflare.com
                - https://*.cloudflare.com
                - https://client-api.arkoselabs.com
                - https://www.google-analytics.com
                - https://cloudflareinsights.com
                - https://www.gstatic.com
                - https://maps.googleapis.com
                - https://maps.gstatic.com
                - https://www.google.com

            frame-src:
                - https://challenges.cloudflare.com
                - https://www.google.com

            object-src:
                - "'none'"

            base-uri:
                - "'self'"
