twig:
    file_name_pattern: "*.twig"

    # ðŸ”‘ Variables globales accessibles dans tous les templates Twig
    globals:
        turnstile_site_key: "%env(TURNSTILE_SITE_KEY)%"

when@test:
    twig:
        strict_variables: true
